<a href="https://colab.research.google.com/github/jaiswalakshant03-cloud/AI-ML-INTERNSHIP/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(a+b)

[5 7 9]


In [5]:
print(a-b)

[-3 -3 -3]


In [6]:
print(a*b)

[ 4 10 18]


In [7]:
print(a/b)

[0.25 0.4  0.5 ]


In [8]:
print(a**3) # square

[ 1  8 27]


In [9]:
print(np.sqrt(a)) # to find the sq root

[1.         1.41421356 1.73205081]


In [10]:
print(np.power(a,2)) # for n exponent

[1 4 9]


In [11]:
arr = np.array([10,20,30,40,50]) # defining 1d array

In [12]:
print(np.mean(arr)) # to find the average

30.0


In [13]:
print(np.median(arr)) # to find median value

30.0


In [14]:
print(np.max(arr)) # highest value

50


In [15]:
print(np.min(arr)) # lowest value

10


In [16]:
print(np.sum(arr)) # total value

150


In [17]:
print(np.std(arr)) # standard deviation

14.142135623730951


In [18]:
print(np.var(arr)) # variance

200.0


In [19]:
arr = np.array([1,2,3,4,5,6])

print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [20]:
arr = np.array([[1,2],[3,4]])

print(arr.flatten())

[1 2 3 4]


In [21]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.arange(1,11) # array in particular range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.random.rand(5) # give random numbers below 1

array([0.93908731, 0.71472693, 0.75840936, 0.16675674, 0.10931752])

In [27]:
np.random.randint(1,100,10) # give random integers

array([17, 83, 85, 86, 77,  2, 62, 66, 51, 78])

In [28]:
arr = np.array([5,2,9,1])

print(np.sort(arr))

[1 2 5 9]


In [29]:
arr = np.array([1,2,2,3,3,4])

print(np.unique(arr))

[1 2 3 4]


In [30]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [31]:
arr = np.array([1,2,3,4,5,6])

print(np.split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [32]:
arr = np.array([10,20,30,40,50])

print(arr[arr>25])

[30 40 50]
